symfony:
  build: symfony/
  volumes:
    - ./symfony/code:/var/www

nginx:
  build: nginx/
  ports:
    - 8080:80
  links:
    - fpm
  volumes_from:
    - symfony
  environment:
    <APP_SERVER_NAME>: dev-machine

fpm:
  build: php-fpm/
  volumes_from:
    - symfony
  environment:
    APP_SERVER_NAME: dev-machine
