services:
    invoice_pdf.service:
        class: PdfFormBundle\Service\InvoicePDFService
#    pdf_form.example:
#        class: PDFFormBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
